services:
  - type: web
    name: tunsrom-fabrics-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false        # you set this manually in Render dashboard
      - key: JWT_SECRET
        sync: false        # you set this manually in Render dashboard
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: ADMIN_EMAIL
        sync: false        # you set this manually in Render dashboard
      - key: ADMIN_PASSWORD
        sync: false        # you set this manually in Render dashboard
      - key: FRONTEND_URL
        sync: false        # your Vercel URL e.g. https://tunsrom-fabrics.vercel.app
